=== mustafaemirata/Dokuman-Tipleri-ve-Veri-Formatlari/Veri Formatları - BTK/xsd_schema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!-- ROOT ELEMENT -->
    <xs:element name="ogrenciler">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ogrenci" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- CHILD ELEMENT -->
    <xs:element name="ogrenci">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="isim" type="xs:string"/>
                <xs:element name="Numara" type="xs:integer"/>
                <xs:element name="Okul" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:integer" use="required"/>
            <xs:attribute name="sinif" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== mustafaemirata/Dokuman-Tipleri-ve-Veri-Formatlari/Veri Formatları - BTK/xsd_ornek.xml
<?xsd version="1.0" encoding="UTF-8" ?>

<ogrenciler xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="xsd_schema.xsd">
    <ogrenci id="1">
        <isim>Orhan</isim>
        <Numara>12</Numara>
        <Okul>Mustafa Kemal Atatürk İlkokulu</Okul>
    </ogrenci>
    <ogrenci id="39">
        <isim>Kemal</isim>
        <Numara>352</Numara>
        <Okul>Mustafa Kemal Atatürk İlkokulu</Okul>
    </ogrenci>
</ogrenciler>
